states = ('Gujarat','MP','UP','MP','AP')
print(states)
print("count of MP = ",states.count("MP"))
print("count of UP = ",states.count("UP"))
print("count of Punjab = ",states.count("Punjab"))
print("position of AP = ",states.index("AP"))
# print("position of Punjab = ",states.index("Punjab"))
print("Good bye")