gods = ("Bramha","Shiv","Vishnu")
devtas = ('indra','agnidev','vayudev','varundev')
print(gods)
print(devtas)
print(gods + devtas)
print(gods * 3)
print(gods[0])
print(gods[0:2])
print(gods[1:])
print(gods)